name: Rust

on:
  push:
    branches: [ rewrite ]
  pull_request:
    branches: [ rewrite ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps: # Setting up SSH key
      - name: Get SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_CAVE }}
          known_hosts: 'placeholder'

      # Adding hosts for CD
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.CAVE_IP }} >> ~/.ssh/known_hosts

      # Install the needed rust toolchain
      - name: Add toolchain
        run: rustup toolchain install --profile minimal nightly-x86_64-unknown-linux-gnu

      # Prepares rustup for wasm compiler
      - name: Add wasm-target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      # Pulls in git dependencies
      - uses: actions/checkout@v3
      - name: Pull git depends
        run: git submodule update --init --recursive --remote

      # Loads cargo cache
      - uses: actions/cache@v3
        name: Pull Cargo cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Builds wasm setup
      - name: Build
        run: ./trunk build

#      # Get goatcounter js for self hosting
#      - name: Download count.js
#        run: wget "https://gc.zgo.at/count.js" -P dist/

#      # Create dummy file for successful removal of any file
#      - name: Create dummy file
#        run: ssh flareflo-github@${{ secrets.CAVE_IP }} 'cd /var/www/nightly_flo_wt_calc; touch placeholder.txt'
#
#      # Clean up dist folder before pushing new set
#      - name: Prepare server for rsync
#        run: ssh flareflo-github@${{ secrets.CAVE_IP }} 'rm -rf /var/www/nightly_flo_wt_calc/*'
#
#      - name: Deploy with rsync
#        run: rsync -avz ./dist/ flareflo-github@${{ secrets.CAVE_IP }}:/var/www/nightly_flo_wt_calc/dist
